<?php
/**
 * Asset file for hesabe-blocks script.
 * This file is auto-generated by @wordpress/scripts.
 * 
 * If you're manually creating this, ensure dependencies match your build setup.
 */
return array(
	'dependencies' => array( 'wp-element', 'wp-html-entities', 'wc-blocks-registry', 'wc-settings' ),
	'version'      => defined( 'WC_HESABE_VERSION' ) ? WC_HESABE_VERSION : '4.0',
);
